'use strict';
const topicsGrid=document.getElementById('topicsGrid'),coursesGrid=document.getElementById('coursesGrid'),videosGrid=document.getElementById('videosGrid'),documentsGrid=document.getElementById('documentsGrid');
const search=document.getElementById('learnSearch'),clear=document.getElementById('clearSearch'),message=document.getElementById('searchMessage'),empty=document.getElementById('noResults'),reset=document.getElementById('resetSearch');
const sections={courses:document.getElementById('coursesSection'),videos:document.getElementById('videosSection'),documents:document.getElementById('documentsSection')};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;");
const norm=v=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
function duration(v){return AgropediaEducation.formatDuration(v);}
function card(item,type){const el=document.createElement('a');el.className='learning-card';el.href=`${type==='courses'?'curso':type==='videos'?'video':'documento'}.html?id=${encodeURIComponent(item.id)}`;const topics=AgropediaEducation.topicNames(item,type==='courses'?'curso_temas':type==='videos'?'video_temas':'documento_temas');el.dataset.search=norm(`${item.titulo} ${item.descripcion||''} ${topics.join(' ')}`);el.innerHTML=`<div class="learning-card__visual">${type==='courses'?'📚':type==='videos'?'🎥':'📄'}</div><div class="learning-card__body"><span class="learning-card__tag">${esc(topics[0]||item.dificultad||'Agropedia')}</span><h3>${esc(item.titulo)}</h3><p>${esc(item.descripcion||'')}</p><div class="learning-card__meta"><span>${esc(duration(item.duracion_minutos))}</span><span>Explorar →</span></div></div>`;return el;}
function renderTopics(data){topicsGrid.innerHTML='';(data||[]).forEach(t=>{const a=document.createElement('a');a.className='topic-card';a.href=`tema.html?tema=${encodeURIComponent(t.slug)}`;a.innerHTML=`<div class="topic-card__icon">🌱</div><div><h3>${esc(t.nombre)}</h3><p>${esc(t.descripcion||'Explora contenido sobre este tema.')}</p></div>`;topicsGrid.appendChild(a);});}
function renderGroup(items,container,type){container.innerHTML='';(items||[]).forEach(x=>container.appendChild(card(x,type)));}
function filter(){const q=norm(search.value);let n=0;Object.values(sections).forEach(section=>{const cards=section.querySelectorAll('.learning-card');let local=0;cards.forEach(c=>{const ok=!q||c.dataset.search.includes(q);c.classList.toggle('hidden',!ok);if(ok){n++;local++;}});section.classList.toggle('hidden',!!q&&!local);});empty.classList.toggle('hidden',n>0);message.textContent=q?`${n} resultado(s) para “${search.value.trim()}”.`:'Explora todo el contenido disponible en Agropedia.';}
async function init(){try{const [t,c,v,d]=await Promise.all([AgropediaEducation.getTopics(),AgropediaEducation.getCourses(),AgropediaEducation.getVideos(),AgropediaEducation.getDocuments()]);if(t.error||c.error||v.error||d.error)throw(t.error||c.error||v.error||d.error);renderTopics(t.data);renderGroup(c.data,coursesGrid,'courses');renderGroup(v.data,videosGrid,'videos');renderGroup(d.data,documentsGrid,'documents');filter();if(!c.data?.length&&!v.data?.length&&!d.data?.length)message.textContent='Todavía no hay contenido educativo publicado. El administrador podrá agregarlo desde el dashboard.';}catch(e){console.error(e);message.textContent='No pudimos cargar el contenido educativo.';empty.classList.remove('hidden');}}
search.addEventListener('input',filter);clear.addEventListener('click',()=>{search.value='';filter();search.focus();});reset.addEventListener('click',()=>{search.value='';filter();});
init();