'use strict';
const type=(new URLSearchParams(location.search).get('tipo')||'cursos');
const config={cursos:{title:'Cursos',heading:'Todos los cursos',icon:'🎓',phrase:'Avanza a tu ritmo y convierte cada aprendizaje en experiencia.'},videos:{title:'Videos',heading:'Todos los videos',icon:'🎥',phrase:'Aprende viendo, observando y llevando cada idea a la práctica.'},documentos:{title:'Documentos',heading:'Todos los documentos',icon:'📚',phrase:'Consulta material de estudio para profundizar cuando lo necesites.'}};
const cfg=config[type]||config.cursos;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;");let items=[];
function duration(v){return AgropediaEducation.formatDuration(v);}
function renderHero(){$('catalogTitle').textContent=cfg.title;$('catalogPhrase').textContent=cfg.phrase;$('catalogIcon').textContent=cfg.icon;$('catalogHeading').textContent=cfg.heading;document.title=`${cfg.title} | Agropedia`;}
async function loadTopics(){const r=await AgropediaEducation.getTopics();if(r.error)throw r.error;(r.data||[]).forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.nombre;$('topicFilter').appendChild(o);});}
async function load(){const fn=type==='cursos'?'getCourses':type==='videos'?'getVideos':'getDocuments';const r=await AgropediaEducation[fn]();if(r.error)throw r.error;items=r.data||[];render();}
function render(){const grid=$('catalogGrid');grid.innerHTML='';items.forEach(x=>{const rel=type==='cursos'?'curso_temas':type==='videos'?'video_temas':'documento_temas';const topics=(x[rel]||[]).map(y=>y.temas?.nombre).filter(Boolean);const card=document.createElement('a');card.className='catalog-card';card.href=`${type==='cursos'?'curso':type==='videos'?'video':'documento'}.html?id=${encodeURIComponent(x.id)}`;card.dataset.search=(`${x.titulo} ${x.descripcion||''} ${topics.join(' ')}`).toLowerCase();card.dataset.topic=(x[rel]||[]).map(y=>y.tema_id).join(',');card.dataset.difficulty=x.dificultad;card.innerHTML=`<div class="catalog-card__visual">${type==='cursos'?'📚':type==='videos'?'🎥':'📄'}</div><div class="catalog-card__body"><div class="catalog-card__tags"><span class="catalog-card__tag">${esc(topics[0]||'Agropedia')}</span><span class="catalog-card__tag catalog-card__tag--difficulty">${esc(x.dificultad)}</span></div><h3>${esc(x.titulo)}</h3><p>${esc(x.descripcion||'')}</p><div class="catalog-card__meta"><span>${esc(duration(x.duracion_minutos))}</span><span>Explorar →</span></div></div>`;grid.appendChild(card);});filter();}
function filter(){const q=$('catalogSearch').value.toLowerCase().trim(),t=$('topicFilter').value,d=$('difficultyFilter').value;let n=0;document.querySelectorAll('.catalog-card').forEach(c=>{const ok=(!q||c.dataset.search.includes(q))&&(t==='all'||c.dataset.topic.split(',').includes(t))&&(d==='all'||c.dataset.difficulty===d);c.classList.toggle('hidden',!ok);if(ok)n++;});$('catalogEmpty').classList.toggle('hidden',n>0);$('catalogResultsMessage').textContent=`${n} resultado(s) encontrados.`;}
function reset(){ $('catalogSearch').value='';$('topicFilter').value='all';$('difficultyFilter').value='all';filter();}
$('catalogSearch').addEventListener('input',filter);$('topicFilter').addEventListener('change',filter);$('difficultyFilter').addEventListener('change',filter);$('clearCatalogSearch').addEventListener('click',()=>{$('catalogSearch').value='';filter();});$('resetCatalogFilters').addEventListener('click',reset);$('emptyResetButton').addEventListener('click',reset);
renderHero();Promise.all([loadTopics(),load()]).catch(e=>{console.error(e);$('catalogResultsMessage').textContent='No pudimos cargar el catálogo.';});
