(() => {
'use strict';

const monthNames=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
const recommendedByMonth={1:['Lechuga','Zanahoria','Rábano','Espinaca','Cilantro'],2:['Jitomate','Lechuga','Zanahoria','Rábano','Cilantro'],3:['Jitomate','Pepino','Calabacita','Albahaca','Frijol'],4:['Jitomate','Pepino','Calabacita','Chile','Albahaca'],5:['Pepino','Calabacita','Chile','Frijol','Albahaca'],6:['Pepino','Calabacita','Frijol','Maíz','Chile'],7:['Jitomate','Pepino','Frijol','Chile','Albahaca'],8:['Jitomate','Lechuga','Rábano','Cilantro','Zanahoria'],9:['Lechuga','Espinaca','Rábano','Zanahoria','Cilantro'],10:['Lechuga','Espinaca','Zanahoria','Rábano','Ajo'],11:['Espinaca','Lechuga','Zanahoria','Rábano','Ajo'],12:['Lechuga','Espinaca','Cilantro','Rábano','Zanahoria']};
const plantEmoji=['🌱','🥬','🥕','🌿','🍅'];
let carouselIndex=0;

function season(date){const m=date.getMonth()+1,d=date.getDate();if((m===3&&d>=20)||m>3&&m<6||(m===6&&d<21))return ['Primavera','Buen momento para renovar el suelo y comenzar nuevos cultivos.'];if((m===6&&d>=21)||m>6&&m<9||(m===9&&d<23))return ['Verano','Prioriza el riego, el acolchado y la protección frente al calor.'];if((m===9&&d>=23)||m>9&&m<12||(m===12&&d<21))return ['Otoño','Ideal para preparar el suelo y establecer cultivos de temporada fresca.'];return ['Invierno','Protege los cultivos sensibles al frío y aprovecha para planear la próxima temporada.'];}

function moonPhase(date){const known=new Date(Date.UTC(2000,0,6,18,14));const days=(date.getTime()-known.getTime())/86400000;const age=((days%29.530588853)+29.530588853)%29.530588853;const names=['Luna nueva','Luna creciente','Cuarto creciente','Luna gibosa creciente','Luna llena','Luna gibosa menguante','Cuarto menguante','Luna menguante'];const icons=['●','◔','◑','◕','○','◕','◑','◔'];const i=Math.floor((age/29.530588853)*8+0.5)%8;return {name:names[i],icon:icons[i],age};}

function renderCalendarInfo(){const now=new Date();const [s,sd]=season(now);const moon=moonPhase(now);document.getElementById('current-month').textContent=monthNames[now.getMonth()];document.getElementById('popular-month').textContent=monthNames[now.getMonth()];document.getElementById('season-name').textContent=s;document.getElementById('season-description').textContent=sd;document.getElementById('moon-name').textContent=moon.name;document.getElementById('moon-icon').textContent=moon.icon;document.getElementById('moon-description').textContent='Ciclo lunar aproximado · día '+Math.round(moon.age)+' de 29.5';}

function timeAdvice(){const now=new Date(),h=now.getHours(),m=now.getMinutes(),s=now.getSeconds();const time=document.getElementById('current-time');time.textContent=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':');time.dateTime=now.toISOString();let period,advice;if(h>=5&&h<8){period='Mañana';advice='El sol aún es suave. Revisa la humedad del suelo y riega temprano para reducir la evaporación.'}else if(h>=8&&h<12){period='Mañana';advice='Con luz creciente, revisa hojas y tallos. Retira hojas dañadas y observa señales tempranas de plagas.'}else if(h>=12&&h<17){period='Mediodía';advice='Evita trabajar intensamente el suelo bajo el calor. Mantén el acolchado y revisa que las plantas no sufran estrés hídrico.'}else if(h>=17&&h<20){period='Tarde';advice='Es un buen momento para revisar el huerto y, si hace falta, realizar un riego moderado cuando el calor haya disminuido.'}else{period='Noche';advice='Deja descansar el huerto. Observa la humedad y planifica las tareas de mañana en lugar de regar de más.'}const [s]=season(now),moon=moonPhase(now);if(s==='Verano'&&h>=8&&h<17)advice+=' En verano, prioriza conservar la humedad del suelo.';if(s==='Invierno'&&h<8)advice+=' En invierno, evita regar cuando pueda producirse una helada.';if(moon.name==='Luna nueva'||moon.name==='Luna menguante')advice+=' Esta fase puede ser un buen momento para labores de mantenimiento y preparación.';if(moon.name==='Luna llena')advice+=' Observa especialmente el estado de las plantas y la humedad del suelo.';document.getElementById('time-period').textContent=period;document.getElementById('garden-advice').textContent=advice;}

function renderCarousel(){const month=new Date().getMonth()+1;const plants=recommendedByMonth[month];const track=document.getElementById('plant-track');track.innerHTML=plants.map((p,i)=>`<article class="plant-card"><div class="plant-card__image">${plantEmoji[i]}</div><div class="plant-card__body"><h3>${p}</h3><p>Recomendada para ${monthNames[month-1]}.</p></div></article>`).join('');const dots=document.getElementById('carousel-dots');dots.innerHTML=plants.map((_,i)=>`<button class="carousel-dot ${i===0?'is-active':''}" type="button" aria-label="Mostrar planta ${i+1}" data-slide="${i}"></button>`).join('');dots.querySelectorAll('.carousel-dot').forEach(b=>b.addEventListener('click',()=>{carouselIndex=Number(b.dataset.slide);moveCarousel()}));document.getElementById('carousel-prev').addEventListener('click',()=>{carouselIndex=(carouselIndex+plants.length-1)%plants.length;moveCarousel()});document.getElementById('carousel-next').addEventListener('click',()=>{carouselIndex=(carouselIndex+1)%plants.length;moveCarousel()});window.addEventListener('resize',moveCarousel);moveCarousel();}
function moveCarousel(){const track=document.getElementById('plant-track'),card=track.querySelector('.plant-card');if(!card)return;const gap=18;const width=card.getBoundingClientRect().width+gap;const max=Math.max(0,track.children.length-(window.innerWidth<=650?1:window.innerWidth<=900?3:5));carouselIndex=Math.min(carouselIndex,max);track.style.transform=`translateX(-${carouselIndex*width}px)`;document.querySelectorAll('.carousel-dot').forEach((d,i)=>d.classList.toggle('is-active',i===carouselIndex));}

function renderPopular(){const body=document.getElementById('popular-plants');body.innerHTML=Array.from({length:10},(_,i)=>`<tr><td>${i+1}</td><td>Por definir</td><td>—</td><td>—</td></tr>`).join('');}

function init(){renderCalendarInfo();timeAdvice();renderCarousel();renderPopular();setInterval(()=>{timeAdvice();renderCalendarInfo()},1000);}
document.addEventListener('DOMContentLoaded',init);
})();
